description: "Introductory Python course for Humanities Researchers at Uni Potsdam"
email: "digital-humanities@uni-potsdam.de"
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
